name: Reusable Push to ACR
on:
  workflow_call:
    inputs:
      acr_username:
        required: true
        type: string
      acr_password:
        required: true
        type: string
      acr_servername:
        required: true
        type: string

jobs:
  acr_push:
    name: push artifacts to ACR
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world from REUSER WORKFLOW!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo username: ${{ inputs.username }}
          echo ${{ inputs.username }}
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.ACR_USER }}
          # Container registry password
          password: ${{ secrets.ACR_PASS }}
          # Container registry server url
          login-server: ${{ secrets.ACR_SERVER }} 
       - run:   
          docker push ${{ secrets.ACR_SERVER }}/tomcat_gv:${{ github.run_id }}
