name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
  #  secrets:
  #    token:
  #      required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
 
          
      - name: Run a one-line script
        run: echo Hello, world from REUSER WORKFLOW!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo username: ${{ inputs.username }}
          echo ${{ inputs.username }}
#      - uses: ./.github/actions/my-action@v1
#         with:
#           username: ${{ inputs.username }}
#           token: ${{ secrets.token }}  
