name: Reusable Push to ACR
on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
      dockerfile_name:
        required: true
        type: string  
      acr_packagename:
        required: true
        type: string
      acr_packagetag:
        required: true
        type: string
    secrets:
      acr_username:
        required: true
      acr_password:
        required: true
      acr_servername:
        required: true
        
jobs:
  acr_build_push:
    name: push artifacts to ACR
    runs-on: ubuntu-latest
    steps:
      
      # Runs a set of commands using the runners shell
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo packagename_sent_to_push: ${{ inputs.acr_packagename }}
          pwd
          ls -lart
          docker ps
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.acr_username }}
          # Container registry password
          password: ${{ secrets.acr_password }}
          # Container registry server url
          login-server: ${{ secrets.acr_servername }} 
           
      - run: |
         
         docker build -f Dockerfile . -t ${{ secrets.ACR_SERVER}}/${{acr_packagename}}:${{github.run_id }}
         docker push ${{ secrets.ACR_SERVER }}/${{acr_packagename}}:${{ github.run_id }}
         #docker push ${{ secrets.acr_servername }}/${{inputs.acr_packagename }}
